/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AutomationRouteImport } from './routes/automation'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as MeetingsRouteImport } from './routes/meetings'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SmsOutreachRouteImport } from './routes/sms-outreach'
import { Route as ApiPublicUnsubscribeRouteImport } from './routes/api/public/unsubscribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationRoute = AutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetingsRoute = MeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SmsOutreachRoute = SmsOutreachRouteImport.update({
  id: '/sms-outreach',
  path: '/sms-outreach',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUnsubscribeRoute = ApiPublicUnsubscribeRouteImport.update({
  id: '/api/public/unsubscribe',
  path: '/api/public/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/clients': typeof ClientsRoute
  '/generator': typeof GeneratorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/sms-outreach': typeof SmsOutreachRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/clients': typeof ClientsRoute
  '/generator': typeof GeneratorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/sms-outreach': typeof SmsOutreachRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/automation': typeof AutomationRoute
  '/clients': typeof ClientsRoute
  '/generator': typeof GeneratorRoute
  '/invoices': typeof InvoicesRoute
  '/leads': typeof LeadsRoute
  '/meetings': typeof MeetingsRoute
  '/settings': typeof SettingsRoute
  '/sms-outreach': typeof SmsOutreachRoute
  '/api/public/unsubscribe': typeof ApiPublicUnsubscribeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/automation'
    | '/clients'
    | '/generator'
    | '/invoices'
    | '/leads'
    | '/meetings'
    | '/settings'
    | '/sms-outreach'
    | '/api/public/unsubscribe'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/automation'
    | '/clients'
    | '/generator'
    | '/invoices'
    | '/leads'
    | '/meetings'
    | '/settings'
    | '/sms-outreach'
    | '/api/public/unsubscribe'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/automation'
    | '/clients'
    | '/generator'
    | '/invoices'
    | '/leads'
    | '/meetings'
    | '/settings'
    | '/sms-outreach'
    | '/api/public/unsubscribe'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AutomationRoute: typeof AutomationRoute
  ClientsRoute: typeof ClientsRoute
  GeneratorRoute: typeof GeneratorRoute
  InvoicesRoute: typeof InvoicesRoute
  LeadsRoute: typeof LeadsRoute
  MeetingsRoute: typeof MeetingsRoute
  SettingsRoute: typeof SettingsRoute
  SmsOutreachRoute: typeof SmsOutreachRoute
  ApiPublicUnsubscribeRoute: typeof ApiPublicUnsubscribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automation': {
      id: '/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meetings': {
      id: '/meetings'
      path: '/meetings'
      fullPath: '/meetings'
      preLoaderRoute: typeof MeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sms-outreach': {
      id: '/sms-outreach'
      path: '/sms-outreach'
      fullPath: '/sms-outreach'
      preLoaderRoute: typeof SmsOutreachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/unsubscribe': {
      id: '/api/public/unsubscribe'
      path: '/api/public/unsubscribe'
      fullPath: '/api/public/unsubscribe'
      preLoaderRoute: typeof ApiPublicUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AutomationRoute: AutomationRoute,
  ClientsRoute: ClientsRoute,
  GeneratorRoute: GeneratorRoute,
  InvoicesRoute: InvoicesRoute,
  LeadsRoute: LeadsRoute,
  MeetingsRoute: MeetingsRoute,
  SettingsRoute: SettingsRoute,
  SmsOutreachRoute: SmsOutreachRoute,
  ApiPublicUnsubscribeRoute: ApiPublicUnsubscribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
